name: Daily KPI to Slack

on:
  schedule:
    # ⏰ 09:15 KST = 00:15 UTC
    - cron: "15 0 * * *"
  workflow_dispatch:  # 수동 실행 버튼

permissions:
  contents: read

jobs:
  post-kpi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Playwright 브라우저 설치
      - name: Install Playwright (chromium)
        run: python -m playwright install --with-deps chromium

      - name: Post KPI to Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          # 필요하면 아래처럼 추가할 수도 있어요 (선택)
          # BISKIT_DASHBOARD_URL: https://biskit.devskrf.cloud/crci/core-kpi/overview/summary/daily
          # USE_YESTERDAY: "1"
        run: python kpi_to_slack.py
